title: Panduka Wijesundara
logo: /assets/img/headshot_circle.png
description: Data Strategist / Associate ML Engineer (GenAI, NLP, CV) | Freelancer
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
